#define TASK_READY	0x0
#define TASK_WAIT_READ	0x1
#define TASK_WAIT_WRITE	0x2
#define TASK_READ	0x3
#define TASK_WRITE	0x4

#define TASK_NUM_LIMIT  8
#define TASK_STACK_SIZE 1024
#define PRESERVE_REGSET 32+2

#define PIPE_NUM_LIMIT		16
#define PATH_NUM_RESERVED	3
#define PATH_NAME_MAX		64

#define MKFIFO_FD		0
#define PATHSERVER_FD		(TASK_NUM_LIMIT+PATH_NUM_RESERVED)

#define SYSTICK_CONTROL 	*(volatile int *)(0x0E100000)
#define SYSTICK_RELOAD_VALUE 	*(volatile int *)(0x0E100004)
#define SYSTICK_STATUS	 	*(volatile int *)(0x0E101000)
#define SYSTICK_CURRENT_VALUE 	*(volatile int *)(0x0E101004)
#define SYSTICK_CONTROL_ENABLE       1
#define SYSTICK_CONTROL_CLEAR        2
#define SYSTICK_CONTROL_CONTINUOUS   4

